### ISSUE TITLE
Please upgrade to Python3 and Tensorflow 1.0

### ISSUE THREAD

**Issue by kice** [Jongchan/tensorflow-vdsr#12]
TensorFlow 1.0 only support Windows with Python 3.5 installed and there are some api changes since TF 1.0 was releases.

**Comment by Jongchan** [comment]
There have been several requests for upgrading the code.
I will update the code for the recent Tensorflow ASAP, including some more features (multi-gpu, tensorboard). I cannot guarantee upgrading for Python 3.x, but I will take a look at it.

Until then, I will keep this issue alive.

**Comment by Jongchan** [comment]
The only change needed for new tf version is to change ```tf.sub``` to ```tf.subtract```. It is updated for tf 1.1 now.
Python 3.x is still not supported.

**Comment by jiangxuetao0823** [comment]
TensorFlow 1.0 only support Windows with Python 3.5 installed

**Comment by jiangxuetao0823** [comment]
TensorFlow 1.0 only support Windows with Python 3.5 installed，Why U can updated code for tf 1.1 but Python 3.x is still not supported.
