### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by caglayantuna** [Jongchan/tensorflow-vdsr#14]
When I run VDSR.py, it prints num thread :0. Does it mean I can't use multithreading? Because I have GTX750 Ti and training time takes almost 55 hours.

**Comment by Jongchan** [comment]
Actually, there is a serious problem with the code (for handling threads), and update is in progress.
I will comment again as soon as I update the code.
(the training time seems fine)

**Comment by Jongchan** [comment]
I've checked the code, and you are doing okay. If you can carefully look into the code, actually the number of threads are printed before adding the threads. The weird printing line was added to check the ```del threads[:]``` is working fine.
