### ISSUE TITLE
PLOT unexpected behavior

### ISSUE THREAD

**Issue by kevinzying** [Jongchan/tensorflow-vdsr#19]
If you run TEST on two different test datasets using two different checkpoints (say, you run dataset 1 on checkpoints after 15 and 20 epochs and run dataset 2 on checkpoints after 0 and 30 epochs), then PLOT will correctly only append the relevant checkpoint results to each dataset. However, this leads to the behavior of the number which is played NOT matching up with the correct checkpoint. 

e.g. np.argmax(vdsr_mean_2) would probably give (1, 1, 1) as the max for both dataset 1 and dataset 2 but it should give (1, 1, 1) and then (3, 3, 3).

Any simple fixes?

**Comment by Jongchan** [comment]
Sorry I got back here so late.
At the very beginning of the PLOT.py code, there is a 'glob.glob' that gives the whole list of psnr results.
So, you may change the settings for the glob operation. 
(for example, search for psnr results starting with special prefixes?)

**Comment by kevinzying** [comment]
Yeah, I guess that's what I needed. Thanks!
