### ISSUE TITLE
About Matlab and Python Image Processing

### ISSUE THREAD

**Issue by jackie840129** [Jongchan/tensorflow-vdsr#2]
Hi, I found in this link https://github.com/huangzehao/caffe-vdsr 
that the author check the PSNR with two rgb images.
Can I know the reason that you only check it by the ycbcr image ?
(Probably because that Python cannot correctly change the ycbcr image back to rgb?)
Thanks!

**Comment by Jongchan** [comment]
@jackie840129 
I've read the caffe version code, and I think it uses Y channel to compute PSNR as well.

**Comment by Jongchan** [comment]
If you have no further comments, I will close this issue.
