### ISSUE TITLE
Training time problem

### ISSUE THREAD

**Issue by BUPTLdy** [Jongchan/tensorflow-vdsr#20]
Hello, the `checkpoint` that your provided was trained by the default parameters in the code?
The paper says that network training is done within 4 hours, but I use GTX 1080 and Cuda 8.0, it seem that need several days.

**Comment by Jongchan** [comment]
1) Yes it is trained with the default parameters
2) For me, I am using GTX1080 as well, and it takes several hours to train. 
I don't remember how long it takes exactly, but definitely not more than 12 hours.

**Comment by BUPTLdy** [comment]
I trained with the default parameters, and got the same `checkpoint VDSR_adam_epoch_016.ckpt-57188`
as you provided, but the PSNR is lower 1.5db than your model.
