### ISSUE TITLE
How long does it take to train a new model?

### ISSUE THREAD

**Issue by siemensyf** [Jongchan/tensorflow-vdsr#24]
I have test the code OK with the 'VDSR_adam_epoch_016.ckpt-57188' model provided. However, I have some problem in training a new model.

My question is that it seems take long time to train a new model when I ran VSDR. Unfortunately, I kill the procedure before it returns a new model for me. My test configurations are as follows:
windows7+cuda8.0+nvidia Geforce 740M

Would you please share some information about the training process?

**Comment by Jongchan** [comment]
@siemensyf 
I did my training in Ubuntu 14.04 + CUDA 8.0 + GTX 1080, and it took a few hours to train..
(Unfortunately, it was several months ago, so I cannot recall the actual duration.)

But with 750M, I'm afraid that it will take very long time to train.
