### ISSUE TITLE
is it required GPU for running?

### ISSUE THREAD

**Issue by seasonyang** [Jongchan/tensorflow-vdsr#29]
when i run the script below:
$ python VDSR.py --model_path ./checkpoints/VDSR_adam_epoch_016.ckpt-57188

result:
InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'shared_model/conv_20_b': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.

**Comment by Jongchan** [comment]
Yes current configuration is to use GPUs.
I guess you need to manually set the devices to run it on CPUs.
