### ISSUE TITLE
Is the file extension missed in aug_train.m?

### ISSUE THREAD

**Issue by blueardour** [Jongchan/tensorflow-vdsr#3]
Hi, 

I noticed that train files were save in formart 'aug/%d' in aug_train.m.
However, in VDSR.py, the train_list was generated by scan '.mat' files. So I wondered whether one of them was wrong?

I did not have matlab installed, I employed octave to run the .m file.

**Comment by blueardour** [comment]
seems matlab save file with .mat extension as default

**Comment by Jongchan** [comment]
yes, we need to save in mat format to preserve precision
