### ISSUE TITLE
make_template('shared_model',model)

### ISSUE THREAD

**Issue by EricKani** [Jongchan/tensorflow-vdsr#30]
Hi,
 I have a question about `shared_model = tf.make_template('shared_model', model)` in line 104 in the VDSR.py. Is this operation have some advantages? thank you very much! 
And the second question is whether the way of data_reading in your code can  replace the way of tfrecords?

**Comment by EricKani** [comment]
Hi, 
The first question I think I have solved it. "tf.make_template" is used for the variable sharing, like using "with the tf.variable_scope( ' ', reuse = True)".
Is that right?

**Comment by Jongchan** [comment]
@EricKani Yes, that is correct!
