### ISSUE TITLE
The model seems to have a difference from the paper?

### ISSUE THREAD

**Issue by YongWookHa** [Jongchan/tensorflow-vdsr#38]
In [paper](https://cv.snu.ac.kr/research/VDSR/VDSR_CVPR2016.pdf), the residual block add only once.
The output image with input image.

Is there any reason you used residual block every conv-layer?

**Comment by YongWookHa** [comment]
I am sorry.. I misunderstood your code. 
I'll close this issue.

**Comment by violetsaturn** [comment]
excuse me, i can not find the residual block in this code, Cloud you tell me where is it add in the author's code?  thank you!
