### ISSUE TITLE
How to make a new image with super resolution by your source

### ISSUE THREAD

**Issue by joei1981** [Jongchan/tensorflow-vdsr#4]
I tried to apply your method on my own data and make new images with super resolution. I wonder how to realize such a purpose by your open source ?

**Comment by Jongchan** [comment]
@joei1981 
1) Resize the target image with bicubic interpolation (matlab bicubic preferred)
2) Feed the Y channel of the resized image, and get the enhanced Y channel
3) Replace the resized Y channel with enhanced Y channel.

Basically, the network enhanced the Y channel only.

**Comment by Jongchan** [comment]
If you just want to apply, it would be better to use the original author's test code.

I recommend you to use my code only when you want a tensorflow-based system for SR..

**Comment by joei1981** [comment]
I see. Thank you so much for your advice
